import { loadImage, loadMedia } from './lazyload.js';
import { receivePresentationControls } from './presentation.js';

function buttons(a){const b=document.createElement("div");return b.classList.add("btns"),b.appendChild(downloadImages()),b.appendChild(toggleDisplay(a)),b.appendChild(hiddenPresButton()),b}function buildButton(a,b){const c=document.createElement("button");return c.classList.add(`btns--btn`),c.setAttribute("aria-label",a),c.innerHTML=b,c}function hiddenPresButton(){const a=document.createElement("button");return a.classList.add("btns--hidden"),a.setAttribute("aria-label","Presentation Navigation Keyboard Focus"),a.innerHTML="",a}function downloadImages(){const a=buildButton("Download All Assets","<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"><path d=\"M24.708 13.207l-1.414-1.415L17 18.087V1.5h-2v16.585l-6.292-6.293-1.414 1.415 8.707 8.707z\"/><path d=\"M29 18.5v8H3v-8H1v12h30v-12z\"/></svg>");return a.addEventListener("click",()=>{const b=document.querySelectorAll("picture, img"),c=document.querySelectorAll("video, audio");b.forEach(a=>loadImage(a)),c.forEach(a=>loadMedia(a)),a.parentNode.removeChild(a);}),a}function toggleDisplay(a){const b="<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"><path d=\"M3 6h22v2H3zM3 12h14v2H3zM3 18h26v2H3zM3 24h14v2H3z\"/></svg>",c=buildButton("Toggle Article/Presentation Display",b);return c.addEventListener("click",()=>{a.dispatch("display","toggle");}),a.changes.subscribe("display",a=>{c.innerHTML="presentation"===a.display?b:"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"><path d=\"M19 3h10v10H19z\"/><path d=\"M17 3H3v26h26V15H17V3zm-2 24H5V17h10v10zm12-10v10H17V17h10zM5 15V5h10v10H5z\"/></svg>";}),c}

function buildMinimap(a){const b=document.createElement("nav");return b.classList.add("minimap"),a.forEach(a=>{if(a.first){const a=document.createElement("div");a.classList.add("minimap--section"),b.appendChild(a);}b.lastChild.appendChild(a.progress);}),b}function createMinimapLink(a,b,c,d=!1){const e=document.createElement("a");return e.classList.add("minimap--slide"),e.href=`#/${a}`,e.innerText=`Section ${b}, Slide ${c}`,e.dataset.fragments=d,e}

function keys(a,b={}){document.addEventListener("keydown",c=>{if("presentation"===a.state.display&&!c.target.classList.contains("btns--btn")){const d=spaceMove(c,b);d&&("notes"===d?a.dispatch("notes","toggle"):a.dispatch("navigate",d));}});}function spaceMove(a,b){const c={ctrl:!0===a.ctrlKey,alt:!0===a.altKey,meta:!0===a.metaKey,shift:!0===a.shiftKey};let d=!1,e=!1;if(!1!==b.spacebar){let f=32===a.keyCode,g=f&&c.shift;!0!==b.spacebar&&(f=f&&c[b.spacebar],g=g&&c[b.spacebar]),d=g,e=f;}if(!1!==b.remote){let f=33===a.keyCode,g=34===a.keyCode;!0!==b.remote&&(f=f&&c[b.remote],g=g&&c[b.remote]),d=d||f,e=e||g;}return d?"previous":e?"next":!!(83===a.keyCode&&c.alt&&c.shift)&&"notes"}

function playVideo(a){const b=a.target;b.pause(),b.currentTime=0,a.isIntersecting&&(!b.src&&loadMedia(b),window.setTimeout(()=>{b.play();},200));}function playVideoObserver(a){a.forEach(a=>{playVideo(a);});}function autoplay(){const a=document.querySelectorAll("video[data-autoplay]");if("IntersectionObserver"in window){const b=new IntersectionObserver(playVideoObserver);a.forEach(a=>b.observe(a));}}

function upgrade(a,b,c,d){a._head.elem.querySelector("._stage--content").insertAdjacentElement("beforebegin",buttons(this.store)),a.buildProgress(this.store,createMinimapLink),b.parentNode.appendChild(buildMinimap(a)),this.goto(c),keys(this.store,d),autoplay(),receivePresentationControls(this.store);}

export { upgrade };
//# sourceMappingURL=upgrade.js.map
